### ISSUE TITLE
Allow matches to be between players

### ISSUE THREAD

**Issue by BenjaminHunt** [adammast/RSCBot#100]
In the `match` prefix, matches are scheduled between teams.

For 1v1 leagues, where players have independent schedules, it would be ideal to have the ability to schedule matches between players the same way that matches are currently scheduled between teams.

This may involve updating a chain of dependencies in the `match` cog.

**Comment by BenjaminHunt** [comment]
This may not be necessary...

**Comment by adammast** [comment]
The format for the 1v1 league has changed to the point where this update is not necessary anymore. This can be reopened in the future if the desire to create matches between players arises again.
