### ISSUE TITLE
Handle GM transactions better

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#54]
For transactions involving a GM, the franchise and tier roles need to persist and no prefix should be added to them.

There needs to be a check for whether the member is a GM in the following functions within the transactions cog:
-sub
-add_player_to_team
-remove_player_from_team

**Comment by BenjaminHunt** [comment]
It appears that these transactions handle role management a little awkwardly. For example, the `?cut` command uses the `remove_player_from_team` function, which removes the franchise role. However, the rest of the `?cut` command adds Free Agent roles and changes the nickname. Is there a reason this behavior is split?

I see that `?promote` uses `remove_player_from_team`, but it also uses `add_player_to_team`, which would immediately change the nickname back.

**Comment by BenjaminHunt** [comment]
Also, just to clarify... you said that "no prefix should be added," but to be more accurate, we'd want a GM's franchise prefix to persist--or remain unchanged, regardless of the transaction, correct?

**Comment by adammast** [comment]
Up until this season GM's didn't have their franchise prefix, which is why I wrote it that way. For now just make it so we don't change their prefix, so correct.

**Comment by adammast** [comment]
This has been completed with the recent updates for the 1v1 league. The GM now gets their tier role removed/added for cut/signing but their franchise role persists along with their prefix.
