### ISSUE TITLE
Add command to remove all tiers at once

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#63]
In the teamManager cog there are commands for managing tiers. Right now there is a removeTier command for removing one tier at a time. There should also be a command to remove all the tiers at once. Name this new command "clearTiers". For functionality I'd suggest looking at the removeTier command as well as the clearTeams command.

**Comment by BenjaminHunt** [comment]
Should this remove the roles associated with the existing tiers? If there isn't a clear option, perhaps adding an optional flag/parameter that indicates the roles tiers should be removed as well.

**Comment by adammast** [comment]
This should really just call the removeTier method in a loop for each tier, so since that removes the tier roles I'd have it do the same. Only difference here is I'd confirm that the user wants to remove all tiers and their roles first. The confirmation can be a quick reaction event similar to the ones we have in the sixMans cog.

**Comment by BenjaminHunt** [comment]
the transferFranchise PR adds a helper message for confirmation reactions that will help with this.
