### ISSUE TITLE
Tier Role should not be removed after a substitution for Free Agents

### ISSUE THREAD

**Issue by BenjaminHunt** [adammast/RSCBot#65]
At the end of a Free Agent substitution, the tier role should not be removed.
For example, if a `ProspectFA`/`Prospect` player subs for a `Prospect` team, they should not lose the `Prospect` role when the substitution is complete. #

**Comment by BenjaminHunt** [comment]
I don't think I can label this as a bug without being an official contributor.

**Comment by BenjaminHunt** [comment]
I'm not sure how to label this as a `bug`.

**Comment by adammast** [comment]
We should also handle cases where a free agent is temp subbed to a higher tier. For example, in my testing I made my self a ChallengerFA but subbed up to a Minor team. After unsubbing, I was left with both the Challenger and Minor tier roles. I think we'll need to check what tier they should have based on their FA role.
![Capture](https://user-images.githubusercontent.com/8559035/82122241-4ea03c00-9760-11ea-9ded-da70bc5a87cc.PNG)

**Comment by BenjaminHunt** [comment]
Good point.

**Comment by BenjaminHunt** [comment]
I've noticed something else as well. If a challengerFA subs for a minor team, they appear on the franchise's challenger and minor roster. A small issue, but worth keeping in mind.

**Comment by adammast** [comment]
We can use the tierFA role as a source of truth for what their original tier is. Then when subbed up, remove all tier roles and add only the one for the team they are subbing to. After subbing, remove all tier roles again and add back only the one they should have based on their tierFA role. We should check if the player has a tierFA role first though, and if they don't then handle it the way we currently are.
