### ISSUE TITLE
Error handling and removing queue after the queue channel no longer exists

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#67]
If the discord channel for a queue is deleted the sixMans cog will throw errors anytime any queue data is changed. We need better error handling in the _save_queues method for queues with no channels. Right now the only way to fix this issue is to figure out which queue is missing a channel and edit it to point to a different text channel. What I'd want is for a custom error message to alert me to exactly which queue is messed up, then allow me to remove that queue using the existing removeQueue command.

**Comment by BenjaminHunt** [comment]
What if the bot just created a replacement channel if the q channel gets deleted and points to that channel for us?
