### ISSUE TITLE
Fix search for Free Agent role in sub command

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#78]
In the method get_tier_role_for_fa we try to remove the Free Agent role from the list of fa_roles. The list must be missing the Free Agent role though because it gives an error saying that role is missing from the list. Here's the trace of the error:
![Capture](https://user-images.githubusercontent.com/8559035/83086882-f02b6580-a05d-11ea-927e-324cc381e8b0.PNG)

**Comment by BenjaminHunt** [comment]
I'm not sure why I had that line of code. I will investigate.

**Comment by BenjaminHunt** [comment]
I'll check it out

**Comment by adammast** [comment]
I should specify, the error occurs when signing or subbing a player that doesn't have the role named "Free Agent". Since there's no guarantee that every free agent has that role, we shouldn't assume that it'll be in their list of roles. we should check if it exists in the list before trying to remove it: https://stackoverflow.com/questions/4915920/how-to-delete-an-item-in-a-list-if-it-exists

**Comment by BenjaminHunt** [comment]
That's what I was thinking. I assumed all FAs would have the FA role. When wouldn't they? I can add a check though, it's probably a good measure either way.

**Comment by adammast** [comment]
PermFAs often don't get the Free Agent role. I think that's just user human error because their roles are given to them manually at the moment and the important roles for most of the channels currently are the tierFA roles and the permFA role.

**Comment by BenjaminHunt** [comment]
Interesting. Good to know.
