### ISSUE TITLE
Add command to make a member permFA or change their tier

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#84]
The new command will be named makePermFA and will be functionally similar to the makeDE command and will also be part of the bulkRoleManager cog unless we need to put it in the teamManager cog for some reason. The command will take in a list of members and the name of the tier each member is in as a list of arguments similar to the addTeams command. If the member doesn't already have the PermFA role the member will need the following roles added to them:
- PermFA
- Tier (ex. Challenger)
- TierFA (ex. ChallengerFA)
- League

They will also need to have the "FA" prefix added to their nickname.

If the member is already a permFA we want to check if the given tier role is different than their current tier role. If so, we want to remove their old tier roles and replace them with the new tier roles. We also want to send them a dm explaining that their tier has changed. The message will have this wording:
"__**Message from [Guild Name]:**__

Congrats! Due to your recent ranks you've been promoted to our [Tier Name] tier! You'll only be allowed to play in that tier or any tier above it for the remainder of this season. If you have any questions please let an admin know.

If you checked in already for the next match day, please use the commands [Prefix]co to check out and then [Prefix]ci check in again for your new tier."

**Comment by BenjaminHunt** [comment]
This does look fun.
