### ISSUE TITLE
6mans - sync text channel perms

### ISSUE THREAD

**Issue by adammast** [adammast/RSCBot#88]
When a new text channel is generated by the bot for a 6mans game, sync the perms for the new channel with the perms for the 6mans category. If there is no category set in that guild, continue to normal channel generation.

**Comment by BenjaminHunt** [comment]
This should be pretty simple. When the category is generated, be sure to pass `permissions_synced=True`. I'm surprised that isn't the default... I did something similar in the combineRooms cog.
